version: '3.8'

services:
  api-manager:
    build: .
    container_name: api-manager-container
    ports:
      - "8080:8080"
    environment:
      - COGNITO_ISSUER_URI=${COGNITO_ISSUER_URI}
      - COGNITO_CLIENT_ID=34f47e0ai20b9u6e8srd2fnphm
    restart: always